basePath: /
definitions:
  entities.BlockUserResponse:
    properties:
      message:
        type: string
      unblocked_user_id:
        type: integer
    type: object
  entities.BlockedUsersList:
    properties:
      blocked_at:
        type: string
      blocked_user_id:
        type: string
      userid:
        type: string
    type: object
  entities.BlockedUsersListResponse:
    properties:
      Message:
        type: string
      blocked_users_list:
        items:
          $ref: '#/definitions/entities.BlockedUsersList'
        type: array
      fetched_at:
        type: string
    type: object
  entities.BlockingUser:
    properties:
      blocked_at:
        type: string
      blocked_user_id:
        type: integer
    required:
    - blocked_user_id
    type: object
  entities.GetImagesResponse:
    properties:
      images:
        items:
          $ref: '#/definitions/entities.Image'
        type: array
      message:
        type: string
    type: object
  entities.GetProfileDetailsResponse:
    properties:
      additional_email:
        type: string
      blocked_users_amount:
        type: integer
      education:
        type: string
      followers:
        type: integer
      following:
        type: integer
      message:
        type: string
      origin:
        type: string
      profileimage:
        items:
          type: integer
        type: array
      userid:
        type: string
      working_place:
        type: string
    type: object
  entities.GetTrustedDevices:
    properties:
      device_list:
        items:
          $ref: '#/definitions/entities.TrustedDevices'
        type: array
      message:
        type: string
    type: object
  entities.GetUserInfoResponse:
    properties:
      additional_email:
        type: string
      blocked_users_amount:
        type: integer
      education:
        type: string
      email:
        type: string
      first_name:
        type: string
      followers:
        type: integer
      following:
        type: integer
      ip_address:
        type: string
      last_name:
        type: string
      message:
        type: string
      origin:
        type: string
      password:
        type: string
      personal_number:
        type: string
      phonenum:
        type: string
      profileimage:
        items:
          type: integer
        type: array
      salt:
        items:
          type: integer
        type: array
      user_id:
        type: integer
      user_name:
        type: string
      working_place:
        type: string
    required:
    - email
    - first_name
    - ip_address
    - last_name
    - password
    - personal_number
    - phonenum
    - user_name
    type: object
  entities.Image:
    properties:
      imageid:
        type: string
      isprofileimage:
        type: boolean
      profileimage:
        type: string
      uploadedat:
        type: string
    type: object
  entities.RegisteredUserResponse:
    properties:
      created_at:
        type: string
      message:
        type: string
      user_id:
        type: integer
    type: object
  entities.ResetPassword:
    properties:
      email:
        type: string
      personal_number:
        type: string
      username:
        type: string
    required:
    - email
    - personal_number
    - username
    type: object
  entities.ResetPasswordResponse:
    properties:
      message:
        type: string
      user_id:
        type: string
    type: object
  entities.SignedInUserResponse:
    properties:
      access_token:
        type: string
      access_token_exp:
        type: string
      message:
        type: string
      refresh_token:
        type: string
      refresh_token_exp:
        type: string
    type: object
  entities.TrustedDevices:
    properties:
      device_id:
        type: integer
      device_identifier:
        type: string
      device_ip_address:
        type: string
      device_name:
        type: string
      userid:
        type: string
    required:
    - device_name
    type: object
  entities.TrustedDevicesResponse:
    properties:
      message:
        type: string
      userid:
        type: string
    type: object
  entities.UnblockUserResponse:
    properties:
      message:
        type: string
      unblocked_user_id:
        type: integer
    type: object
  entities.UnblockingUser:
    properties:
      unblocked_user_id:
        type: integer
    required:
    - unblocked_user_id
    type: object
  entities.UploadProfileImageResponse:
    properties:
      message:
        type: string
      uploaded_at:
        type: string
    type: object
  entities.UserInputWithoutID:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  entities.UserRegInput:
    properties:
      email:
        type: string
      first_name:
        type: string
      ip_address:
        type: string
      last_name:
        type: string
      password:
        type: string
      personal_number:
        type: string
      phonenum:
        type: string
      user_name:
        type: string
    required:
    - email
    - first_name
    - ip_address
    - last_name
    - password
    - personal_number
    - phonenum
    - user_name
    type: object
  entities.ValidateResetEmail:
    properties:
      password:
        type: string
      personal_number:
        type: string
      validation_code:
        type: string
    required:
    - password
    - personal_number
    - validation_code
    type: object
  entities.ValidateResetPasswordResponse:
    properties:
      message:
        type: string
      reset_date:
        type: string
    type: object
  handler.localError:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Endpoints for Authorization, Account, Settings, Payments
  title: E_Commerce Microservices
  version: "0.1"
paths:
  /api/auth/add-trusted-device:
    post:
      consumes:
      - application/json
      description: Adds Trusted Devices (Device IP)
      operationId: add-trusted-device
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.TrustedDevices'
      produces:
      - application/json
      responses:
        "205":
          description: Reset Content
          schema:
            $ref: '#/definitions/entities.TrustedDevicesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      security:
      - ApiKeyAuth: []
      summary: Add Trusted Device
      tags:
      - Protected - Account
  /api/auth/block-user:
    post:
      consumes:
      - application/json
      description: Block User By ID
      operationId: block-user
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.BlockingUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.BlockUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      security:
      - ApiKeyAuth: []
      summary: Block User
      tags:
      - Protected - Account
  /api/auth/refresh-login:
    post:
      consumes:
      - application/json
      description: Refresh Login - Refreshes AccessToken
      operationId: refresh-login
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.SignedInUserResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.ValidateResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      security:
      - ApiKeyAuth: []
      summary: Refresh Login Handler
      tags:
      - Auth
  /api/auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset Password Outside From Account
      operationId: reset-password
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.ResetPassword'
      produces:
      - application/json
      responses:
        "205":
          description: Reset Content
          schema:
            $ref: '#/definitions/entities.ResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Reset Password Handler
      tags:
      - Auth
  /api/auth/reset-password-profile:
    post:
      consumes:
      - application/json
      description: Reset Password From The Account
      operationId: reset-password-profile
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.ValidateResetEmail'
      produces:
      - application/json
      responses:
        "205":
          description: Reset Content
          schema:
            $ref: '#/definitions/entities.ValidateResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      security:
      - ApiKeyAuth: []
      summary: Reset Password Profile Handler
      tags:
      - Auth
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Login An User
      operationId: login-user
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.UserInputWithoutID'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.SignedInUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: SignIn Handler
      tags:
      - Auth
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Create An User
      operationId: create-user
      parameters:
      - description: User Info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.UserRegInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.RegisteredUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: SignUp Handler
      tags:
      - Auth
  /api/auth/unblock-user:
    post:
      consumes:
      - application/json
      description: Add Profile Image (Uploading Multiple Times Is Acceptable)
      operationId: upload-profile-image
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.UploadProfileImageResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UploadProfileImageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      security:
      - ApiKeyAuth: []
      summary: Upload Profile Image
      tags:
      - Protected - Account
  /api/auth/verify-reset-email:
    post:
      consumes:
      - application/json
      description: Validation Of Reset Password (Code Is Sent To Gmail)
      operationId: validate-reset-password
      parameters:
      - description: Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.ValidateResetEmail'
      produces:
      - application/json
      responses:
        "205":
          description: Reset Content
          schema:
            $ref: '#/definitions/entities.ValidateResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.localError'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/handler.localError'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Validate Reset Password Mail Handler (Code)
      tags:
      - Auth
  /api/protected/account/blocked-user-list:
    get:
      consumes:
      - application/json
      description: Gets Blocked Users List
      operationId: blocked-users-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.BlockedUsersListResponse'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Get Blocked Users List
      tags:
      - Protected - Account
  /api/protected/account/get-images:
    get:
      consumes:
      - application/json
      description: Get Uploaded Images
      operationId: uploaded-images
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.GetImagesResponse'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Get Images
      tags:
      - Protected - Account
  /api/protected/account/profile-details:
    get:
      consumes:
      - application/json
      description: Gets User Profile Details
      operationId: user-profile-details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.GetProfileDetailsResponse'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Get Profile Details
      tags:
      - Protected - Account
  /api/protected/account/trusted-devices-list:
    get:
      consumes:
      - application/json
      description: Get Trusted Devices List
      operationId: trusted-device
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.GetTrustedDevices'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Get Trusted Devices
      tags:
      - Protected - Account
  /api/protected/account/user-info:
    get:
      consumes:
      - application/json
      description: Get User Info
      operationId: user-info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.GetUserInfoResponse'
        "500":
          description: Internal Server Error
          schema:
            type: default
      summary: Get User Info
      tags:
      - Protected - Account
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
