name: Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build Docker Image
        run: docker build . --tag b-microServices:$(date + %s)

      -name: Publish to Registry
       uses: davitdarsalia/Publish_Docker-Github-Action@master
       with:
         name: BComerce/go-github-actions
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}